### ISSUE TITLE
I want to ask something.

### ISSUE THREAD

**Issue by arcpuree** [jeeliz/jeelizGlassesVTOWidget#19] opened 2019-11-11 14:24 UTC
1. If I need to insert new glasses, what do I need to prepare?
2. Can I create my own glasses database? If i can do What do I have to do.

thank you.

**Comment by xavierjs** [comment] 2019-11-11 15:18
Duplicate of #3

**Closed by xavierjs** 2019-11-11 15:18 UTC

**Comment by arcpuree** [comment] 2019-11-11 15:38
thank you
