### ISSUE TITLE
Invalid Sku 

### ISSUE THREAD

**Issue by alianjum351** [jeeliz/jeelizGlassesVTOWidget#15] opened 2019-07-16 10:46 UTC
it was working fine before but now its giving me the error of "INVALID SKU" exception. I did not change anything in the file (demo.html). I am looking forward to attach it with my website. we can discuss that later. I am gonna present this software to my company...maybe they'll buy it. but for now this error coming up. resolve this issue 
best regards
Ali

**Comment by xavierjs** [comment] 2019-07-16 17:19
Duplicate of #11 and #13 
The server crashed, I am investingating why. I am sorry for this inconvenience. Moreover it happens during my day off. The service will be back very soon

**Comment by xavierjs** [comment] 2019-07-16 17:59
It should be working now :) I close the issue, feel free to re-open it if it happens again.
Best,
Xavier

**Closed by xavierjs** 2019-07-16 17:59 UTC
