### ISSUE TITLE
Is it possible to add my own 3d model glasses and store in my server?

### ISSUE THREAD

**Issue by deryan12** [jeeliz/jeelizGlassesVTOWidget#17] opened 2019-07-22 23:14 UTC
Hi, 
is it possible to add my own 3d glasses models, or it's neccessary to use only your 390 models?

Thanks for your response

**Comment by xavierjs** [comment] 2019-07-22 23:59
Duplicate of #3

**Closed by xavierjs** 2019-07-22 23:59 UTC
