### ISSUE TITLE
Don't work on safari 11.1

### ISSUE THREAD

**Issue by max-websecret** [jeeliz/jeelizGlassesVTOWidget#1] opened 2018-05-17 08:00 UTC
Safari 11.1 version error on console. 
![2018-05-17 10 59 16](https://user-images.githubusercontent.com/12588034/40164186-883aaa6a-59c1-11e8-8cff-41b5e67e1bdd.png)

**Comment by xavierjs** [comment] 2018-05-17 15:14
Hello,

Thank you for your bug reporting. I think it is more a driver/OS problem but I think there is a workaround I am working on it :).
This is linked to this problem : https://bugs.webkit.org/show_bug.cgi?id=169999

**Comment by xavierjs** [comment] 2018-05-17 15:44
I think I have corrected the bug (I cannot check because I do not have a desktop mac, I am a Linux user).
Can you check again after cleanning your browser cache ? Thank you very much !

**Comment by max-websecret** [comment] 2018-05-17 16:08
Now little bit better)
I see request for using camera and then error in console, I attached screenshot
![2018-05-17 19 07 36](https://user-images.githubusercontent.com/12588034/40189661-ac70eff4-5a05-11e8-9dda-4463533fae8a.png)

**Comment by xavierjs** [comment] 2018-05-17 17:00
I think I have found the bug. Can you try again ? Thank you very much for your patience !

**Comment by max-websecret** [comment] 2018-05-18 06:27
No( the same error
![2018-05-18 09 26 38](https://user-images.githubusercontent.com/12588034/40219360-a530f5b8-5a7d-11e8-90a7-7a35fc05ef07.png)

**Comment by xavierjs** [comment] 2018-05-18 14:29
Thank you for you screenshot. This bug makes me crazy, in the unpacked code I have :
```
try {
   //the line which triggers the first error :
   GL.texImage2D(GL.TEXTURE_2D, 0, internalPixelFormat, 2,2, 0, GL.RGBA, pixelType, data);
} catch(e){
  return false;
}
//this line which triggers the second error, so the first error is not catched !!!!!!!!!!!!! WTF ?
GL.generateMipmap(GL.TEXTURE_2D);
```
Still looking for this !

**Comment by xavierjs** [comment] 2018-05-18 15:39
I have improved the error catching, it may work now. Can you try this special debug version (with much more logging informations !) : [https://jeeliz.com/demos/widgetDebug/indexDebug.html](https://jeeliz.com/demos/widgetDebug/indexDebug.html)

Thank you very much !

**Comment by max-websecret** [comment] 2018-05-18 16:51
No(
![2018-05-18 19 50 48](https://user-images.githubusercontent.com/12588034/40247355-c953c7a2-5ad4-11e8-95aa-b77cacd80b48.png)

**Comment by xavierjs** [comment] 2018-05-18 18:56
Can you please try this version : [https://jeeliz.com/demos/widgetDebug3/indexDebug.html](https://jeeliz.com/demos/widgetDebug3/indexDebug.html) ?
And display all the messages in the web console (not only the error messages) by selecting right option atop the javascript console ?
I am testing on a desktop mac with Safari and I cannot reproduce the error :( .
Maybe it is a webcam error. Is your webcam busy with other programs like Skype for example ?
Thank you very much !

**Comment by max-websecret** [comment] 2018-05-21 06:28
![2018-05-21 09 28 39](https://user-images.githubusercontent.com/12588034/40293392-61068f16-5cd9-11e8-86d3-dc7c4d668ef7.png)

**Comment by xavierjs** [comment] 2018-05-21 16:10
Hi,
Thank you for your screenshot.
But although it seems to be an error, it should be catched and non blocking (at the initialization we test the capabilities of your GPU to choose the best settings) so unfortunately I cannot debug with this information.
Can you enable the display of ALL messages, not only the errors (I think it is the BCE button). This is a screenshot under macOSX of safari 11.1 with the last demo  ( [https://jeeliz.com/demos/widgetDebug3/indexDebug.html](https://jeeliz.com/demos/widgetDebug3/indexDebug.html) ). I draw a red arrow pointing to the button to display all console messages and copy paste the console messages here ? 
Have you tried this WebRTC test : [https://simpl.info/getusermedia/](https://simpl.info/getusermedia/) ? Does it display the video of your webcam ?

<img width="2043" alt="githubbug" src="https://user-images.githubusercontent.com/1659000/40317604-43fe0d10-5d22-11e8-81c2-fef9226106f1.png">

**Comment by max-websecret** [comment] 2018-05-21 16:17
Ha) On my browser don't work https://simpl.info/getusermedia/ too)
And screenshot with all messages in console
![2018-05-21 19 17 26](https://user-images.githubusercontent.com/12588034/40317929-a73229da-5d2b-11e8-8305-9aa4865ff513.png)
![Uploading Скриншот 2018-05-21 19.17.22.png…]()

**Comment by xavierjs** [comment] 2018-05-21 16:21
This is a problem with the webcam drivers or maybe the webcam is busy (used by another program like skype). But there is still a bug in our side because we should switch to the fallback version where you can upload a picture only and it is processed server-side. I am investigating...

**Comment by xavierjs** [comment] 2018-05-21 16:41
Can you post the screenshot of all console messages of [https://jeeliz.com/demos/widgetDebug3/libGetUserMedia/](https://jeeliz.com/demos/widgetDebug3/libGetUserMedia/)
This is a basic test of our getUserMedia wrapper. It should only display the video from the webcam.
After loading can you also try to click on the document ?

Thank you very much

**Comment by max-websecret** [comment] 2018-05-22 07:10
![2018-05-22 10 10 11](https://user-images.githubusercontent.com/12588034/40347267-56029112-5da8-11e8-860c-3590f28ae721.png)

**Comment by xavierjs** [comment] 2018-05-22 17:52
Hi Max,

Thank you again for your feedbacks and your patience !
Can you try this demo : [https://jeeliz.com/demos/widgetDebug3/libGetUserMedia2/](https://jeeliz.com/demos/widgetDebug3/libGetUserMedia2/) and give me what is logged into the javascript console (all messages, not only the error messages).

Thank you by advance,
Xavier

**Comment by xavierjs** [comment] 2018-05-25 19:34
Hi,

I have done some big code refactoring.
Can you retry the full demo (after having emptied the browser cache or in private navigation mode) : [https://jeeliz.com/demos/jeelizWidgetGitPublicDemo/](https://jeeliz.com/demos/jeelizWidgetGitPublicDemo/) 
And if it does not work (no video or no error handling),
try this test : [https://jeeliz.com/demos/tests/libGetUserMedia/](https://jeeliz.com/demos/tests/libGetUserMedia/) and give me the content of the javascript console (all messages, not only the error messages) ?

Thank you very much,
Xavier

**Comment by max-websecret** [comment] 2018-05-26 14:51
It's work! Very good) I'm happy) Thank very much)

And check please my question on email from max@websecret.by

**Comment by xavierjs** [comment] 2018-05-27 16:36
Thank you very much for you help, we have solved also the problem on our other apis (like https://github.com/jeeliz/jeelizFaceFilter). I have not received your email. Mine is xavier@jeeliz.com

Cheers,
Xavier

**Comment by xavierjs** [comment] 2018-06-09 16:36
I close the issue because it seems it is resolved. Thank you very much for your help !

**Closed by xavierjs** 2018-06-09 16:36 UTC
