### ISSUE TITLE
Regarding SKU models of Glasses

### ISSUE THREAD

**Issue by namanmanocha7** [jeeliz/jeelizGlassesVTOWidget#30] opened 2020-09-11 22:18 UTC
Hi,
Hope you are doing Great & Keeping well!!!
I am reaching for creating virtual try-on utilising JEELIZ. 
I want to implement similar solution for my client so, how can I use JEELIZ APIs to do same.
While exploring on github I got to we can customise SKU models in our application. 
Can you please provide technical support or pricing model if there is any.

Thank-you.

**Comment by xavierjs** [comment] 2020-09-14 13:41
Duplicate of #3

**Closed by xavierjs** 2020-09-14 13:41 UTC
