### ISSUE TITLE
Invalid SKU

### ISSUE THREAD

**Issue by roshen986** [jeeliz/jeelizGlassesVTOWidget#13] opened 2019-04-27 15:17 UTC
I keep getting an error which says Invalid SKU, but I'm pretty sure I've done almost everything accurately.

**Comment by xavierjs** [comment] 2019-04-27 17:33
Duplicate of #11 
The mongodb server crashed again, it is a weird bug.
I think I have been a bit cheap on the RAM of the server, I will fix it.
The services have been restarted, it should work now.

**Closed by xavierjs** 2019-04-27 17:33 UTC

**Comment by alianjum351** [comment] 2019-07-16 00:12
I keep getting an error which says Invalid SKU, it was working fine before but now it keep giving me this error..
