### ISSUE TITLE
What’s the process for adding new frames?

### ISSUE THREAD

**Issue by amraghib** [jeeliz/jeelizGlassesVTOWidget#12] opened 2019-04-24 09:19 UTC
Hi I am considering using your solution but wondering what is the process of adding new frames? You mentioned I would contact you but I’m sure you wouldn’t have all glasses in the world so how can I myself add a new frame. Do I need special camera equipment to take a picture of the frame and then upload somewhere?

**Comment by xavierjs** [comment] 2019-04-24 14:19
Duplicate of #3

**Closed by xavierjs** 2019-04-24 14:19 UTC
