### ISSUE TITLE
adding my own 3d glass models

### ISSUE THREAD

**Issue by Saad-Faleh-Al-Dosri** [jeeliz/jeelizGlassesVTOWidget#29] opened 2020-09-03 11:01 UTC
Hi,
I am impressed by your try on. Could you explain how i can add my own 3d models to try on with your code?

**Comment by awasthi7** [comment] 2020-09-04 15:07
Upvoted.

**Comment by xavierjs** [comment] 2020-09-07 18:56
Duplicate of #3

**Closed by xavierjs** 2020-09-07 18:56 UTC
